config/routes.rb
Rails.application.routes.draw do
 
  devise_for :admins

  resources :articles do 
    member do 
      get 'crop'
    end
    resource :comments do 
    end
  end
  resources :users
  resources :comments do

  end

  post '/signin', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/articlecrop/:id', to: 'articles#articlecrop'
  post '/articlecroppost/:id', to: 'articles#articlecroppost'

  root 'welcome#index'


end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable#, :trackable, :timeoutable, :lockable

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_attached_file :main_image, styles: {:thumb => ''}
	validates_attachment_content_type :main_image, :content_type => /\Aimage\/.*\Z/
	crop_attached_file :main_image, :aspect => "11:6"
	has_many :comments

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	acts_as_votable

	belongs_to :user
	belongs_to :article
	def score
		self.get_upvotes.size 
	end
	def self.today
    where("created_at >= ?", Time.zone.now.beginning_of_day)
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	belongs_to :article
	belongs_to :cart

	
end

app/models/user.rb
class User < ActiveRecord::Base
	has_attached_file :avatar, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end


def current_user
	if session[:user_id]
		User.find(session[:user_id])
	else
		nil
	end
end



	

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_admin!, only: [:new, :edit, :update, :create, :destroy]

  before_action :set_article, only: [:edit, :update, :show, :destroy, :crop ]
  def index
    @articles = Article.all
  end
  
  def articlecrop
    @article = set_article
  end

  def crop

  end

  def edit

  end

  def new
    @article = Article.new
  end

  def show
    @user = User.all
    @comment = Comment.new

  end

  def create
    @article = Article.create(article_params)
    if @article.save
      render :crop
    end
  end

  def update
    if @article.update(article_params)
      render :show
    end
  end 

  def destroy
  end

  private

  def set_article 
    @article= Article.find(params[:id])
  end

  def article_params 
    params.require(:article).permit(:name, :description, :main_image, :main_image_original_w, :main_image_original_h, :main_image_box_w, :main_image_crop_x, :main_image_crop_y, :main_image_crop_w, :main_image_crop_h, :main_image_aspect)
  end

  def user_params
  params.require(:user).permit(:avatar)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :set_comment, only: [:edit, :update, :show, :destroy ]

  def index
    @comments = Comment.all
  end

  def edit
  end

  def new
    @article = Article.find(params[:article_id])
    @comment = Comment.new
  end

  def create
    @article = Article.find(params[:article_id])
    @comment = Comment.create(comment_params)
    if @comment.save
      redirect_to article_path(@article.id), notice: "Comment Posted"
    else
      render :new
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to comment_path
    else
      render :edit
    end
  end

  def destroy
  end

   private


   def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:title, :body, :score).merge(user_id: current_user.id).merge(article_id: @article.id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 
  def create
    @user = User.find_by(email: params[:email])
    if @user and @user.password == params[:password]
      flash[:notice] = "Successfully signed in!"
      session[:user_id] = @user.id
    else
      flash[:alert] = "Something went wrong."
    end
      redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :set_user, only: [:edit, :update, :show, :destroy ]


  def index
    @users = User.all
    
  end

  def new
    @articles = Article.all
    @user = User.new
  end

  def edit

  end

  def show
  end

  def create
    @user = User.create(user_params)
    if @user.save
      redirect_to '/', notice: "New user created"
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to edit_user_path, notice: "User successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to '/', notice: "User deleted."
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :username, :bio, :password, :avatar)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@comments = Comment.all
  	@article = Article.all.paginate(page: params[:page], per_page: 6) 
  	@user = User.all
  end

  private
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/crop.html.erb
<div class="crop-wrapper">
	<p><b>Hold mouse to crop image for slideshow</b></p>
	<%= form_for @article do |f| %>
  		<%= f.cropbox :main_image, :width => 800 %>
  		<%= f.crop_preview :main_image, :width => 400 %><br>
  		<%= f.submit 'Publish Article!' %>
	<% end %>
</div>

app/views/articles/edit.html.erb
<h1>Edit article</h1>


<%= form_for @article, :html => {:multipart => true} do |f| %><b>
	<%= f.label :name %>
	<%= f.text_field :name %><br /><br>

	<%= f.label :description %>
	<%= f.text_area :description %> <br /><br>

	<%= f.label :main_image %><br>
	<%= f.file_field :main_image %><br><br>

	<%=f.submit %></b>


<% end %>

app/views/articles/index.html.erb
<h1 style="text-align:center;">All articles</h1>



<div class="ArticleBackgroundAll">
	<div id="PerArticle">
	<% @articles.order.each do |article| %>

	<%= link_to (image_tag article.main_image.url(:medium)), article_path(article.id) %>

	<br />
	<%= link_to article.name, article_path(article.id) %></h1><br />

	<%= article.description %></p><br />


	<p>
	<hr />

		<%=link_to "#{article.comments.size} Comments", article_path(article.id) %> </p>

	<hr />



<% end %>

</div>



</div>

app/views/articles/new.html.erb
<div class="wrapper">

<h1 class="ArticleNewHead">Add New Article</h1>


<%= form_for @article, :html => {:multipart => true} do |f| %>
	<div class="ArticleUpload">
		<br />
		<%= f.label :Title %><br>
			<%= f.text_field :name %><br><br>
		
		<%= f.label :Body%><br>
			<%= f.text_area :description, :size => "90x10" %>
		<br />

		<%= f.label :main_image %>
			<%= f.file_field :main_image %>

		<br/>
		<input type="submit" name="commit" value="Add Post">
	</div>


	


<% end %>
</div>

app/views/articles/show.html.erb
<div class="postPageTop">

		<h3><%= @article.name %></h3>

		<section class="image-gallery group">
			<figure tabindex="1">
		<%= image_tag @article.main_image.url, :class => "img_large" %>
			</figure>
		</section>


<p class="PageArticle"><%= @article.description %><br><p>
</div>



<div class="commentWrapper">
	<h3>User Comments</h3>
	<div class="comments">
<% @article.comments.each do |comment| %>
		
		<p><%= image_tag comment.user.avatar.url,:class => 'avatar' %>Posted <%=time_ago_in_words (comment.created_at) %> ago  by <%= comment.user.username %><br><br>
			</p>

			<div class="commentBody">
			<p2 style=""><%= comment.body %></p2>
			</div>
			<br />
		<% end %>
		</div>
		<p style="text-align: center;"><%= link_to "Add a comment", new_article_comments_path(@article.id) %><p>
		</div>

app/views/comments/_comment.html.erb
<fieldset>
 <%= form_for @comment do |f| %>
 	<%= f.label :title %>
 	<%= f.text_field :title %> <br /><br />

 	<%= f.label :body %>
 	<%= f.text_area :body %> <br />
 	<%= f.label :score %>
 	<%= f.text_area :score %>
 	<%= f.submit %>


 	<% end %>
 </fieldset>

app/views/comments/new.html.erb
<div class="commentWrapper">
<h3 style="color:#505050 ">Comment on the article!</h3>


<% if current_user %>
 <%= form_for [@article, @comment] do |f| %>
 	<%= f.text_area :body, :size => "100x10", :maxlength => 600, :id => "textBody" %> <br />
 	<p id="counter"></p>
 	<input type="submit" name="commit" value="Add Comment">

 	<% end %>
 	<% else %>
 	<h3 style="color:white">You must be logged in to post comments! <br><%= link_to "Sign up!", new_user_path %></h3>
 	<% end %>


<h3>User comments</h3></b>

	<div class="comments">
<% @article.comments.order(created_at: :desc).each do |comment| %>
		<p> Posted <%=time_ago_in_words (comment.created_at) %> ago  by <%= comment.user.username %><br>
		<%= comment.body %></p>
		

	<% end %>
</div>	
</div>
<style>
	.footer p1{
		margin-top: 1000px;
	}
</style>

<script type="text/javascript">
$('#textBody').keyup(function () {
    var left = 600 - $(this).val().length;
    if (left < 0) {
        left = 0;
    }
    $('#counter').text('Characters left: ' + left);
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
   	<script type="text/javascript" src="<%= asset_path('jquery-1.9.1.min.js') %>"></script>
    <script type="text/javascript" src="<%= asset_path('bootstrap.min.js') %>"></script>
    <script type="text/javascript" src="<%= asset_path('ie10-viewport-bug-workaround.js') %>"></script>
    <script type="text/javascript" src="<%= asset_path('jssor.slider.mini.js') %>"></script>
</head>

<body style="background-color:#222222;">

	<header>
		    <div class="container">

        <nav class="navbar navbar-inverse navbar-static-top" role="navigation" style="margin-bottom: 0px;">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/"><img src="<%= asset_path('logo.png') %>"></a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                      	<div id="userInt">
	    
						<b><% if current_user %>

						<li><%= "Welcome #{current_user.username}!" %></li>
			 			<li><a><%=link_to('Edit Account', edit_user_path(current_user.id), method: :get) %></a></li>
						<li><a><%= link_to( 'Sign out', logout_path, method: :get) %></a></li>

						
						<% else %>	
						<div class="field">	
						<%= form_tag('/signin', method: :post) do |f| %>
						
						<p><%= label_tag :email %><p>
						<p><%= email_field_tag :email  %><p>
						<p><%= label_tag :password %><p>
						<p><%= password_field_tag :password %><p>
						<p><%= submit_tag "Log in", :style => 'width: 60px' %><p>
						<p><b><%= link_to " Sign up", new_user_path %></b><p>
						<% end %>
						<% end %>
				    	
	    					
						 </form>  
		                        </b>
		                    </ul>
		                </div>
		                </div>
		                </div>

		            </div>
		        </nav>
		        		<% if current_admin %>
	    				<p>
</div>					<ul>
						<%= link_to 'Add new article', new_article_path, method: :get, :class => 'admin '  %> |
    						<%= link_to 'sign out admin', destroy_admin_session_path, method: :get  %></ul>
	    					</p>
			    		<% end %>
   </header>
  <div id="logos">
  	<a href="https://twitter.com/SubtleEntropy" target="_blank"><img src="http://i60.tinypic.com/os6aex.jpg" style=" height: 50px;"></a>
  	<a href="https://facebook.com/subtle3ntropy" target="_blank"><img src="http://i61.tinypic.com/2choors.jpg" style=" height: 50px;"></a>
  	<a href="https://33.media.tumblr.com/cdfe0e96bb78e07e52404a5e9784ceee/tumblr_mlft24p09n1rax9obo10_500.gif" target="_blank"><img src="http://i62.tinypic.com/255mii8.jpg"  style=" height: 50px;"></a>
    <p style="float:left; margin-right:10px; margin-left:15%;"><br><b>Follow me!</p></b>

	</div>

</body>
	

<%= yield %>
 <div class="footer">
   	<p1>COPYRIGHT © 2015 Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
   	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
   	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
   	consequat.</p1>
  </div>
</body>
</html>

app/views/users/edit.html.erb
<div id="Account-wrapper">
	<div id="Account-body">
		<h3>Make changes to your account information</h3>
		<p>Your current Avatar image<br><span></span><br>
		<%= image_tag @user.avatar.url, :class => 'avatar' %>

		<%= form_for @user do |f| %>
			<%= f.label :username %>:&nbsp;<br>
			<%= f.text_field :username, :maxlength => 16, :style => 'width: 140px', :id => 'textBody' %>
                <p id="counter"></p>
			<%= f.label :email %>:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>
			<%= f.email_field :email, :style => 'width: 150px' %><br>

			<%= f.label :password %>:&nbsp;&nbsp;<br>
			<%=f.password_field :password, :style => 'width: 150px' %><br><br>
			<%= f.label :'Avatar Image' %>
            <%= f.file_field :avatar %><br>
			<%=f.submit %></p>
			<% end %>
	</div>
</div>


<script type="text/javascript">
$('#textBody').keyup(function () {
    var left = 16 - $(this).val().length;
    if (left < 0) {
        left = 0;
    }
    $('#counter').text(left + ' Characters left');
});
</script>

app/views/users/new.html.erb
<div class="loginWrapper">

<div class="container">

        <div id="slider1_container" style="display: none; margin: 0 auto; position: absolute; width: 600px;
        height: 300px; overflow: hidden; margin-left:auto; margin-right:auto;">

            <!-- Loading Screen -->
            <div u="loading" style=" left: 0px;">
                <div style="filter: alpha(opacity=70); opacity:0.7;

                background-color: #000; left: 0px;width: 500px; 500px;">
                </div>
                <div style="background: url(../img/loading.gif) no-repeat center center;

                left: 0px;width: 500px;height:500px;">
                </div>
            </div>
 
            <div u="slides" style="cursor: default; width: 600px; height: 300px;
            overflow: hidden;">
            <% @articles.all.order(created_at: :desc).first(6).each do |article| %>
            <div>
            <%= image_tag article.main_image.url, :class => "img_large" %>
       
            </div>

        <% end %>
            </div>

             <div class="loginInter"><p>

				<%= form_for @user do |f| %>
                <p style="font-size:8px;">(Usernames must be 16 characters and under)</p>
				<%= f.label :username %>:&nbsp;
				<%= f.text_field :username, :maxlength => 16, :style => 'width: 140px', :id => 'textBody' %>
                <p id="counter"></p>
				<%= f.label :email %>:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<%= f.email_field :email, :style => 'width: 140px; margin-left:-5px;' %>

				<%= f.label :password %>:&nbsp;&nbsp;
				<%=f.password_field :password, :style => 'width: 140px;' %>
                <%= f.label :'Avatar Image' %>
                <%= f.file_field :avatar %><br>
				<%=f.submit %>
                </p>
				<% end %>
			</div>
        </div>
    </div>

</div>

<div class="push"></div>
<style>
    .footer {
        margin-top: 50%;
    }
</style>

<script type="text/javascript">
$('#textBody').keyup(function () {
    var left = 16 - $(this).val().length;
    if (left < 0) {
        left = 0;
    }
    $('#counter').text(left + ' Characters left');
});
</script>

app/views/users/signin.html.erb
<h1>sign in</h1>
<fieldset>
	<%= form_tag('/signin', method: :post) do |f| %>
		<%= label_tag :email %>
		<%= email_field_tag :email  %><br /><br />
		<%= label_tag :password %>
		<%= password_field_tag :password %><br /><br />
		<%= submit_tag "Log in" %>
	</fieldset>

<% end %>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" nt7 content="width=device-width, initial-scale=1">

    <title>Android Master Race</title>

</head>
<body>

    <div class="container">

        <div id="slider1_container" style="display: none; position: relative; margin: 0 auto; width: 850px;
        height: 380px; overflow: hidden;">

            <!-- Loading Screen -->
            <div u="loading" style="position: absolute; top: 0px; left: 0px;">
                <div style="filter: alpha(opacity=70); opacity:0.7; position: absolute; display: block;

                background-color: #000; top: 0px; left: 0px;width: 100%; height:100%;">
                </div>
                
            </div>

            <!-- Slides Container -->
            <div u="slides" style="cursor: default; position: absolute; left: 0px; top: 0px; width: 850px; height: 380px;
            overflow: hidden;">
            <% @article.all.order(created_at: :desc).first(6).each do |article| %>
            <div>
            <p id="slide_title" style="color=white;"><%= link_to (article.name), article_path(article.id) %></p>
            <%= image_tag article.main_image.url(:thumb), :class => "img_large" %>
       
            </div>

        <% end %>
            </div>

            <!-- Bullet Navigator Skin Begin -->
            <style>

                .jssorb05 div, .jssorb05 div:hover, .jssorb05 .av {
                    background: url(<%= asset_path('b05.png') %>) no-repeat;
                    overflow: hidden;
                    cursor: pointer;
                }

                .jssorb05 div {
                    background-position: -7px -7px;
                }

                    .jssorb05 div:hover, .jssorb05 .av:hover {
                        background-position: -37px -7px;
                    }

                .jssorb05 .av {
                    background-position: -67px -7px;
                }

                .jssorb05 .dn, .jssorb05 .dn:hover {
                    background-position: -97px -7px;
                }
            </style>
            <!-- bullet navigator container -->
            <div u="navigator" class="jssorb05" style="position: absolute; bottom: 16px; right: 6px;">
                <!-- bullet navigator item prototype -->
                <div u="prototype" style="POSITION: absolute; WIDTH: 16px; HEIGHT: 16px;"></div>
            </div>
            <!-- Bullet Navigator Skin End -->
            <!-- Arrow Navigator Skin Begin -->
            <style>

                .jssora11l, .jssora11r, .jssora11ldn, .jssora11rdn {
                    position: absolute;
                    cursor: pointer;
                    display: block;
                    background: url(<%= asset_path('a11.png') %>) no-repeat;
                    overflow: hidden;
                }

                .jssora11l {
                    background-position: -11px -41px;
                }

                .jssora11r {
                    background-position: -71px -41px;
                }

                .jssora11l:hover {
                    background-position: -131px -41px;
                }

                .jssora11r:hover {
                    background-position: -191px -41px;
                }

                .jssora11ldn {
                    background-position: -251px -41px;
                }

                .jssora11rdn {
                    background-position: -311px -41px;
                }
            </style>
            <!-- Arrow Left -->
            <span u="arrowleft" class="jssora11l" style="width: 37px; height: 37px; top: 123px; left: 8px;">
            </span>
            <!-- Arrow Right -->
            <span u="arrowright" class="jssora11r" style="width: 37px; height: 37px; top: 123px; right: 8px">
            </span>

        </div>


    <script>

       
    </script>
    <div class="index_body">
    
     <% @article.order(created_at: :desc).each do |article| %>

        <div class="articlesbody">
            <div class="left">
        <%= link_to (image_tag article.main_image.url, :class => "img_small"), article_path(article.id) %></div>
        <p class="more" style="height:100%;">
        <br /><b><%= link_to (article.name), article_path(article.id) %></b><br>    Posted <%=time_ago_in_words (article.created_at) %> ago<br><%= article.description %></p>
	

     <% end %>
    </div>

</div>
<div id="page_turn">
<%= will_paginate @article %>

</div>
</body>
</html>